<?php
/*
 *  Advanced Custom Fields
 *  License Key: b3JkZXJfaWQ9NDAyNDF8dHlwZT1kZXZlbG9wZXJ8ZGF0ZT0yMDE0LTA5LTIxIDIyOjU2OjQw
 *  License type: only for this theme
 *  License account: cihy87@gmail.com
 */

// 1. customize ACF path
add_filter('acf/settings/path', 'my_acf_settings_path');

function my_acf_settings_path( $path ) {

    // update path

    $path = INC_PLUGIN_DIR . DS . 'acf-pro' . DS;

    // return
    return $path;

}

// 2. customize ACF dir
add_filter('acf/settings/dir', 'my_acf_settings_dir');

function my_acf_settings_dir( $dir ) {

    // update path
    $dir = get_template_directory_uri() . DS . 'plugins' . DS . 'acf-pro' . DS;

    // return
    return $dir;

}

// 3. Hide ACF field group menu item
add_filter('acf/settings/show_admin', '__return_false');

// 4. Include ACF
include_once( INC_PLUGIN_DIR . DS . 'acf-pro' . DS . 'acf.php' );


/*
 * Customize field types
 */

if( function_exists('acf_add_options_page') ) {

    acf_add_options_page(array(
        'page_title' 	=> '',
        'menu_title'	=> 'Opcje strony',
        'menu_slug' 	=> 'acf-options',
        'capability'	=> 'edit_posts',
        'redirect'		=> false
    ));

    acf_add_options_sub_page(array(
        'page_title' 	=> 'Dane kontaktowe',
        'menu_title'	=> 'Dane kontaktowe',
        'parent_slug'	=> 'acf-options',
    ));

    acf_add_options_sub_page(array(
        'page_title' 	=> 'Układ na stronie głównej',
        'menu_title'	=> 'Układ na stronie głównej',
        'parent_slug'	=> 'acf-options',
    ));

}

//if( function_exists('acf_add_options_sub_page') )
//{
//
//    acf_add_options_sub_page(array(
//        'title' => 'Nagłówek i teksty',
//        'parent' => 'edit.php?post_type=uczestnicy',
//        'capability' => 'manage_options'
//    ));
//
//    acf_add_options_sub_page(array(
//        'title' => 'Nagłówek i teksty',
//        'parent' => 'edit.php?post_type=kalkulator',
//        'menu_slug' 	=> 'acf-options-naglowek-i-teksty-k',
//        'capability' => 'manage_options'
//    ));
//
//}

/*
 * Define fields
 */

if( function_exists('acf_add_local_field_group') ):

        /* Standard page options  */

        acf_add_local_field_group(array (
            'key' => 'group_54ce060be564e',
            'title' => 'Główne ustawienia strony',
            'fields' => array (
                array (
                    'key' => 'field_54ce064442384',
                    'label' => '',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<h2 style="background: #222; color: #FFF; padding: 4px 9px; text-transform: uppercase; font-weight: 900;margin: -25px -15px -15px -15px;">Wymiary widoku strony</h2>',
                    'esc_html' => 0,
                ),
                array (
                    'key' => 'field_54d111ba5c4d2',
                    'label' => 'page width',
                    'name' => 'page_width',
                    'type' => 'number',
                    'instructions' => '0 = full screen',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => 0,
                    'max' => 9999,
                    'step' => 1,
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_54ce06de42386',
                    'label' => '',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<h2 style="background: #222; color: #FFF; padding: 4px 9px; text-transform: uppercase; font-weight: 900;margin: -25px -15px -15px -15px;">Grafiki</h2>',
                    'esc_html' => 0,
                ),
                array (
                    'key' => 'field_54d112005c4d4',
                    'label' => 'favicon',
                    'name' => 'favicon',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'full',
                    'library' => 'all',
                    'min_width' => 0,
                    'min_height' => 0,
                    'min_size' => 0,
                    'max_width' => 0,
                    'max_height' => 0,
                    'max_size' => 0,
                    'mime_types' => '',
                ),
                array (
                    'key' => 'field_54d1120e5c4d5',
                    'label' => 'grafika dla udostępniania w socialmedia',
                    'name' => 'share_via_facebook_image',
                    'type' => 'image',
                    'instructions' => 'minimum 1024x1024 PNG',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
    //            array (
    //                'key' => 'field_54ce077b4238a',
    //                'label' => '',
    //                'name' => '',
    //                'type' => 'message',
    //                'instructions' => '',
    //                'required' => 0,
    //                'conditional_logic' => 0,
    //                'wrapper' => array (
    //                    'width' => '',
    //                    'class' => '',
    //                    'id' => '',
    //                ),
    //                'message' => '<h2 style="background: #222; color: #FFF; padding: 4px 9px; text-transform: uppercase; font-weight: 900;margin: -25px -15px -15px -15px;">Social media</h2>',
    //                'esc_html' => 0,
    //            ),
    //            array (
    //                'key' => 'field_54d113085c4d7',
    //                'label' => '',
    //                'name' => '',
    //                'type' => 'message',
    //                'instructions' => '',
    //                'required' => 0,
    //                'conditional_logic' => 0,
    //                'wrapper' => array (
    //                    'width' => '',
    //                    'class' => '',
    //                    'id' => '',
    //                ),
    //                'message' => '<h2 style="background: #222; color: #FFF; padding: 4px 9px; text-transform: uppercase; font-weight: 900;margin: -25px -15px -15px -15px;">Social media</h2>',
    //                'esc_html' => 0,
    //            ),
    //            array (
    //                'key' => 'field_54d113225c4d8',
    //                'label' => 'facebook link',
    //                'name' => 'facebook_link',
    //                'type' => 'url',
    //                'instructions' => '',
    //                'required' => 0,
    //                'conditional_logic' => 0,
    //                'wrapper' => array (
    //                    'width' => '',
    //                    'class' => '',
    //                    'id' => '',
    //                ),
    //                'default_value' => '',
    //                'placeholder' => 'disabled if empty',
    //            ),
    //            array (
    //                'key' => 'field_55e09b343470b',
    //                'label' => 'pinterest link',
    //                'name' => 'pinterest_link',
    //                'type' => 'url',
    //                'instructions' => '',
    //                'required' => 0,
    //                'conditional_logic' => 0,
    //                'wrapper' => array (
    //                    'width' => '',
    //                    'class' => '',
    //                    'id' => '',
    //                ),
    //                'default_value' => '',
    //                'placeholder' => 'disabled if empty',
    //            ),
    //            array (
    //                'key' => 'field_54d1136d5c4da',
    //                'label' => 'twitter link',
    //                'name' => 'twitter_link',
    //                'type' => 'url',
    //                'instructions' => '',
    //                'required' => 0,
    //                'conditional_logic' => 0,
    //                'wrapper' => array (
    //                    'width' => '',
    //                    'class' => '',
    //                    'id' => '',
    //                ),
    //                'default_value' => '',
    //                'placeholder' => 'disabled if empty',
    //            ),
    //            array (
    //                'key' => 'field_54d1138f5c4db',
    //                'label' => 'youtube link',
    //                'name' => 'youtube_link',
    //                'type' => 'url',
    //                'instructions' => '',
    //                'required' => 0,
    //                'conditional_logic' => 0,
    //                'wrapper' => array (
    //                    'width' => '',
    //                    'class' => '',
    //                    'id' => '',
    //                ),
    //                'default_value' => '',
    //                'placeholder' => 'disabled if empty',
    //            ),
    //            array (
    //                'key' => 'field_55e09bbc3470c',
    //                'label' => 'tumblr link',
    //                'name' => 'tumblr_link',
    //                'type' => 'url',
    //                'instructions' => '',
    //                'required' => 0,
    //                'conditional_logic' => 0,
    //                'wrapper' => array (
    //                    'width' => '',
    //                    'class' => '',
    //                    'id' => '',
    //                ),
    //                'default_value' => '',
    //                'placeholder' => 'disabled if empty',
    //            ),
    //            array (
    //                'key' => 'field_54d113545c4d9',
    //                'label' => 'instagram link',
    //                'name' => 'instagram_link',
    //                'type' => 'url',
    //                'instructions' => '',
    //                'required' => 0,
    //                'conditional_logic' => 0,
    //                'wrapper' => array (
    //                    'width' => '',
    //                    'class' => '',
    //                    'id' => '',
    //                ),
    //                'default_value' => '',
    //                'placeholder' => 'disabled if empty',
    //            ),
                array (
                    'key' => 'field_54ce07ec4238c',
                    'label' => '',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<h2 style="background: #222; color: #FFF; padding: 4px 9px; text-transform: uppercase; font-weight: 900;margin: -25px -15px -15px -15px;">STOPKA</h2>',
                    'esc_html' => 0,
                ),
                array (
                    'key' => 'field_54ce08124238dd',
                    'label' => 'Tekst środkowy',
                    'name' => 'text_center',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_54ce08124238du',
                    'label' => 'Nagłówek prawy',
                    'name' => 'right_heading',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_54ce08124238d',
                    'label' => 'copyright',
                    'name' => 'copyright',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array (
                    'key' => 'field_55e04dd4ec8f0',
                    'label' => '',
                    'name' => '',
                    'type' => 'message',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '<h2 style="background: #222; color: #FFF; padding: 4px 9px; text-transform: uppercase; font-weight: 900;margin: -25px -15px -15px -15px;">Panel CMS</h2>',
                    'esc_html' => 0,
                ),
                array (
                    'key' => 'field_55e04df1ec8f1',
                    'label' => 'Pokaż logo autora',
                    'name' => 'show_authorlogo',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

     /* END: Standard page options  */

endif;

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_5666d216d867e',
        'title' => 'Dane kontaktowe',
        'fields' => array (
            array (
                'key' => 'field_5666d26136fa5',
                'label' => 'Telefon',
                'name' => 'telefon',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5666d28236fa6',
                'label' => 'Fax',
                'name' => 'fax',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5666d28936fa7',
                'label' => 'E-mail',
                'name' => 'email',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
            ),
            array (
                'key' => 'field_5666d29336fa8',
                'label' => 'Adres',
                'name' => 'adres',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'wpautop',
                'readonly' => 0,
                'disabled' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-dane-kontaktowe',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_5666ee9fafa14',
        'title' => 'Rozmieszczenie sekcji',
        'fields' => array (
            array (
                'key' => 'field_5666eeb40b5b2',
                'label' => '',
                'name' => 'rozmieszczenie_sekcji',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'page',
                ),
                'taxonomy' => array (
                ),
                'filters' => '',
                'elements' => '',
                'min' => '',
                'max' => '',
                'return_format' => 'id',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-uklad-na-stronie-glownej',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_5666d5a637d88',
        'title' => 'Narzędzie do budowania widoku',
        'fields' => array (
            array (
                'key' => 'field_5666d5dea1c41',
                'label' => '',
                'name' => 'page_builder',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'button_label' => 'Dodaj rząd',
                'min' => '',
                'max' => '',
                'layouts' => array (
                    array (
                        'key' => '5666d5f9e3e53',
                        'name' => 'grafika_z_haslem',
                        'label' => 'Grafika z hasłem',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5666d62ba1c42',
                                'label' => 'Grafika',
                                'name' => 'grafika',
                                'type' => 'image',
                                'instructions' => 'zalecana szerokość 1920px',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'id',
                                'preview_size' => 'heading-image',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array (
                                'key' => 'field_5666d660a1c43',
                                'label' => '',
                                'name' => '',
                                'type' => 'message',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '<h2>Hasło w kwadracie</h2>',
                                'esc_html' => 0,
                            ),
                            array (
                                'key' => 'field_5666d691a1c44',
                                'label' => 'Tytuł',
                                'name' => 'tytul',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666d6ada1c45',
                                'label' => 'Opis',
                                'name' => 'opis',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => 'wpautop',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '5666d6e1a1c46',
                        'name' => 'grafika_z_tytulem',
                        'label' => 'Grafika z tytułem',
                        'display' => 'block',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5666d6e1a1c47',
                                'label' => 'Grafika',
                                'name' => 'grafika',
                                'type' => 'image',
                                'instructions' => 'zalecana szerokość 1920px',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'id',
                                'preview_size' => 'heading-image',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array (
                                'key' => 'field_5666d6e1a1c49',
                                'label' => 'Tytuł',
                                'name' => 'tytul',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '5666d711a1c4b',
                        'name' => 'grafika_tresc',
                        'label' => 'Grafika + treść',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5666d90ba1c56',
                                'label' => 'kolor tła',
                                'name' => 'kolor_tla',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    '#FFFFFF' => 'białe',
                                    '#f5f5f5' => 'szare',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '#FFFFFF : białe',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5666d737a1c4c',
                                'label' => 'Położenie',
                                'name' => 'polozenie',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'textleft' => 'Tekst w lewej kolumnie',
                                    'textright' => 'Tekst w prawej kolumnie',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 'textleft : Tekst w lewej kolumnie',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5666d789a1c4d',
                                'label' => 'Grafika',
                                'name' => 'grafika',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'id',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array (
                                'key' => 'field_5666d79da1c4e',
                                'label' => 'Tytuł',
                                'name' => 'tytul',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666d7b1a1c4f',
                                'label' => 'Treść',
                                'name' => 'tresc',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '5666d7f1a1c50',
                        'name' => 'galeria_grafik',
                        'label' => 'Galeria grafik',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5666d8efa1c55',
                                'label' => 'kolor tła',
                                'name' => 'kolor_tla',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    '#FFFFFF' => 'białe',
                                    '#f5f5f5' => 'szare',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '#FFFFFF : białe',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5666d808a1c51',
                                'label' => 'Liczba kolumn',
                                'name' => 'liczba_kolumn',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    2 => 2,
                                    3 => 3,
                                    4 => 4,
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => 3,
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5666d830a1c52',
                                'label' => 'galeria',
                                'name' => 'galeria',
                                'type' => 'gallery',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'preview_size' => 'thumbnail',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '5666d85ea1c53',
                        'name' => 'tekst',
                        'label' => 'Tekst',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5666d8a1a1c54',
                                'label' => 'kolor tła',
                                'name' => 'kolor_tla',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    '#FFFFFF' => 'białe',
                                    '#f5f5f5' => 'szare',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '#FFFFFF : białe',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5666d953a1c59',
                                'label' => 'Treść',
                                'name' => 'tresc',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '5666d968a1c5a',
                        'name' => 'tabela',
                        'label' => 'Tabela',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5666d968a1c5b',
                                'label' => 'kolor tła',
                                'name' => 'kolor_tla',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    '#FFFFFF' => 'białe',
                                    '#f5f5f5' => 'szare',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '#FFFFFF : białe',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5666da16a1c5e',
                                'label' => 'Kolumna 1',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_5666da43a1c63',
                                'label' => 'Tytuł',
                                'name' => 'kolumna1_tytul',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666d97da1c5d',
                                'label' => 'Wiersze',
                                'name' => 'kolumna1_wiersze',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'layout' => 'table',
                                'button_label' => 'Dodaj wiersz',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5666da7ea1c64',
                                        'label' => 'treść w wierszu',
                                        'name' => 'tresc_w_wierszu',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'readonly' => 0,
                                        'disabled' => 0,
                                    ),
                                ),
                            ),
                            array (
                                'key' => 'field_5666da2da1c62',
                                'label' => 'Kolumna 2',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_5666da97a1c68',
                                'label' => 'Tytuł',
                                'name' => 'kolumna2_tytul',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666dad2a1c6f',
                                'label' => 'Wiersze',
                                'name' => 'kolumna2_wiersze',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'layout' => 'table',
                                'button_label' => 'Dodaj wiersz',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5666dad2a1c70',
                                        'label' => 'treść w wierszu',
                                        'name' => 'tresc_w_wierszu',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'readonly' => 0,
                                        'disabled' => 0,
                                    ),
                                ),
                            ),
                            array (
                                'key' => 'field_5666da2ca1c61',
                                'label' => 'Kolumna 3',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_5666da96a1c67',
                                'label' => 'Tytuł',
                                'name' => 'kolumna3_tytul',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666dad1a1c6d',
                                'label' => 'Wiersze',
                                'name' => 'kolumna3_wiersze',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'layout' => 'table',
                                'button_label' => 'Dodaj wiersz',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5666dad1a1c6e',
                                        'label' => 'treść w wierszu',
                                        'name' => 'tresc_w_wierszu',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'readonly' => 0,
                                        'disabled' => 0,
                                    ),
                                ),
                            ),
                            array (
                                'key' => 'field_5666da2ca1c60',
                                'label' => 'Kolumna 4',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_5666da96a1c66',
                                'label' => 'Tytuł',
                                'name' => 'kolumna4_tytul',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666dad1a1c6b',
                                'label' => 'Wiersze',
                                'name' => 'kolumna4_wiersze',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'layout' => 'table',
                                'button_label' => 'Dodaj wiersz',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5666dad1a1c6c',
                                        'label' => 'treść w wierszu',
                                        'name' => 'tresc_w_wierszu',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'readonly' => 0,
                                        'disabled' => 0,
                                    ),
                                ),
                            ),
                            array (
                                'key' => 'field_5666da2ba1c5f',
                                'label' => 'Kolumna 5',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_5666da95a1c65',
                                'label' => 'Tytuł',
                                'name' => 'kolumna5_tytul',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666dad0a1c69',
                                'label' => 'Wiersze',
                                'name' => 'kolumna5_wiersze',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => '',
                                'max' => '',
                                'layout' => 'table',
                                'button_label' => 'Dodaj wiersz',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5666dad0a1c6a',
                                        'label' => 'treść w wierszu',
                                        'name' => 'tresc_w_wierszu',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                        'readonly' => 0,
                                        'disabled' => 0,
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '5666db16a1c71',
                        'name' => 'opis_i_cena',
                        'label' => 'Opis i cena',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5666db2aa1c72',
                                'label' => 'kolor tła',
                                'name' => 'kolor_tla',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    '#FFFFFF' => 'białe',
                                    '#f5f5f5' => 'szare',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '#FFFFFF : białe',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5666dbd4a1c79',
                                'label' => 'Opis',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_5666db40a1c73',
                                'label' => 'Tytuł',
                                'name' => 'tytul',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666db6ca1c74',
                                'label' => 'Treść',
                                'name' => 'tresc',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array (
                                'key' => 'field_5666dbbea1c78',
                                'label' => 'Cena',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_5666db98a1c76',
                                'label' => 'Tekst przed',
                                'name' => 'tekst_przed',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666db75a1c75',
                                'label' => 'Cena',
                                'name' => 'cena',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                            array (
                                'key' => 'field_5666dba7a1c77',
                                'label' => 'Tekst po',
                                'name' => 'tekst_po',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'readonly' => 0,
                                'disabled' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '5666dc28a1c7a',
                        'name' => 'mapa',
                        'label' => 'Mapa',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5666dc47a1c7c',
                                'label' => 'kolor tła',
                                'name' => 'kolor_tla',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    '#FFFFFF' => 'białe',
                                    '#f5f5f5' => 'szare',
                                ),
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '#FFFFFF : białe',
                                'layout' => 'horizontal',
                            ),
                            array (
                                'key' => 'field_5666dc31a1c7b',
                                'label' => 'map',
                                'name' => 'map',
                                'type' => 'google_map',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'center_lat' => '',
                                'center_lng' => '',
                                'zoom' => '',
                                'height' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '5666dc5ca1c7d',
                        'name' => 'tresc_2_3__1_3',
                        'label' => 'Treść 2/3 + 1/3',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5666dc8ea1c7e',
                                'label' => 'Kolumna 2/3',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_5666ddf2a1c80',
                                'label' => 'tresc23',
                                'name' => 'tresc23',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array (
                                'key' => 'field_5666ddeaa1c7f',
                                'label' => 'Kolumna 1/3',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_5666de01a1c81',
                                'label' => 'tresc13',
                                'name' => 'tresc13',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
            ),
        ),
        'menu_order' => 10,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));

endif;